### ISSUE TITLE
Add ability to not automatically follow redirects

### ISSUE THREAD

**Issue by drzero42** [asciimoo/wuzz#76]
Awesome tool. Currently it automatically follows things like HTTP 301/302/303, which makes it difficult to debug services that do redirects. A way to turn off following redirects would be very nice to have.

**Comment by asciimoo** [comment]
added: 3e3f114

**Comment by drzero42** [comment]
Thanks :)
However, it is not entirely there:
```
$ go get github.com/asciimoo/wuzz
# github.com/asciimoo/wuzz
gocode/src/github.com/asciimoo/wuzz/wuzz.go:1276: undefined: http.ErrUseLastResponse

```

**Comment by asciimoo** [comment]
@drzero42 try to use go >= 1.7

**Comment by drzero42** [comment]
It works with Go 1.7, thank you.
